name: Deploy WordPress to Elastic Beanstalk

on:
  push:
    branches:
      - main # Or your main branch (e.g., main, production)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # Use a Ubuntu runner for the GitHub Actions environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out the repository code so the workflow can access it
        # with:
        #   fetch-depth: 1 # Optional: Shallow clone for faster checkouts

      - name: Set up Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AKIAYDWHTC46I6RMJLXR }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.KARGI5M9ZEjUzAOs/08qCZFjC/7YhxWe2iRySWMa }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.us-east-1 }}" >> $GITHUB_ENV
          echo "EB_APPLICATION_NAME=BITA-Stage" >> $GITHUB_ENV # Replace with your EB application name
          echo "EB_ENVIRONMENT_NAME=BITA-Stage-env" >> $GITHUB_ENV     # Replace with your EB environment name
          echo "DEPLOYMENT_PACKAGE=wordpress.zip" >> $GITHUB_ENV # Define the deployment package name

      - name: Install dependencies
        run: |
          # Update package lists
          sudo apt-get update
          # Install zip (required for creating the deployment package) and the AWS CLI.
          sudo apt-get install -y zip awscli

      - name: Create Deployment Package
        run: |
          #  Create a zip archive of the WordPress files, excluding node_modules and .git.
          zip -r $DEPLOYMENT_PACKAGE . -x "node_modules/*" ".git/*"

      - name: Deploy to Elastic Beanstalk
        run: |
          # Use AWS CLI to deploy the zip file to Elastic Beanstalk.
          # This command assumes that your EB environment is already set up and running.
          aws elasticbeanstalk deploy \
            --application-name "$EB_APPLICATION_NAME" \
            --environment-name "$EB_ENVIRONMENT_NAME" \
            --version-label "$(date +%Y%m%d%H%M%S)" \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1",S3Key="$DEPLOYMENT_PACKAGE" #example
          # Note: The S3 bucket name in the source-bundle parameter is crucial.
          #   It should be in the same region as your Elastic Beanstalk environment.
          #   Elastic Beanstalk often uses a default bucket, but you might need to specify if you have a custom setup.
          #   The S3Key is the name of the zip file.

      - name: Clean up files
        run: |
          # Remove the deployment package after it has been deployed.
          rm $DEPLOYMENT_PACKAGE

